import { FlatCompat } from '@eslint/eslintrc';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import eslintConfigPrettier from 'eslint-config-prettier';
import globals from 'globals';
import vueParser from 'vue-eslint-parser';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const compat = new FlatCompat({
  baseDirectory: __dirname,
});

/** @type {import("eslint").Linter.FlatConfig[]} */
export default [
  {
    ignores: ['.nuxt/**', '.output/**', 'dist/**', 'node_modules/**', 'coverage/**'],
  },

  // Ваш "старый" eslintrc-конфиг через совместимость
  ...compat.config({
    root: true,
    env: {
      browser: true,
      es6: true,
      node: true,
    },
    extends: [
      'standard',
      'plugin:import/errors',
      'plugin:import/warnings',
      'plugin:vue/recommended',
      'eslint:recommended',
      'plugin:sonarjs/recommended',
      'plugin:promise/recommended',
      'plugin:nuxt/recommended',
    ],
    parserOptions: {
      parser: '@babel/eslint-parser',
      ecmaVersion: 'latest',
      requireConfigFile: false,
      sourceType: 'module',
    },
    plugins: ['sonarjs', 'promise'],
    globals: {
      _: false,
    },
    rules: {
      'import/no-named-as-default': 0,
      'comma-dangle': ['error', 'always-multiline'],
      'sonarjs/cognitive-complexity': 0,
      'linebreak-style': 0,
      'promise/no-nesting': 0,
      'vue/script-indent': ['error', 2, { baseIndent: 0 }],
      indent: ['error', 2],
      'vue/html-indent': [
        'error',
        2,
        { attribute: 1, baseIndent: 0, alignAttributesVertically: true },
      ],
      'vue/no-template-shadow': 'error',
      'vue/no-v-html': 'off',
      'vue/padding-line-between-blocks': 'error',
      'vue/require-name-property': 'error',
      'vue/v-on-function-call': 'error',
      'vue/no-reserved-component-names': 'error',
      'vue/no-static-inline-styles': ['error', { allowBinding: false }],
      'import/no-extraneous-dependencies': 'off',
      'lines-between-class-members': 'error',
      'no-unused-expressions': 'error',
      'max-len': ['error', { code: 400 }],
      'no-empty-function': 'error',
      camelcase: 'error',
      'require-await': 'error',
      'no-shadow': ['error', { allow: ['state', 'getters'] }],
      'no-param-reassign': ['error', { ignorePropertyModificationsFor: ['state'] }],
      'import/extensions': 0,
      'arrow-body-style': 0,
      'no-debugger': process.env.NODE_ENV === 'production' ? 'error' : 'off',
      'no-console': process.env.NODE_ENV === 'production' ? 'error' : 'off',
      'no-underscore-dangle': 'off',
      'no-restricted-syntax': 'off',
      'class-methods-use-this': 'off',
      'import/prefer-default-export': 'off',
      'no-unused-vars': [
        'error',
        {
          args: 'none',
          caughtErrors: 'none',
          ignoreRestSiblings: true,
          vars: 'all',
        },
      ],
      'no-use-before-define': ['error', { functions: false, classes: false, variables: false }],
      'no-restricted-globals': 'off',
      'no-bitwise': 'off',
      'func-names': 'off',
      'promise/always-return': 'off',
      'prefer-destructuring': 0,
      'vue/max-attributes-per-line': [
        'error',
        {
          singleline: 2,
          multiline: 1,
        },
      ],
      'no-alert': 'off',
      'no-eval': 'error',
      'no-extend-native': 0,
      curly: ['error', 'all'],
      'no-else-return': 0,
      'no-eq-null': 'error',
      'no-extra-parens': 'error',
      'no-labels': 'error',
      'no-new': 'error',
      'no-new-func': 'error',
      'no-new-wrappers': 'error',
      'no-loss-of-precision': 'error',
      'max-classes-per-file': ['error', 1],
      'no-constructor-return': 'error',
      'no-promise-executor-return': 'error',
      'array-callback-return': 'error',
      'no-extra-bind': 'error',
      'no-implicit-coercion': 'error',
      'no-implicit-globals': 'error',
      'no-implied-eval': 'error',
      'no-invalid-this': 'off',
      'no-lone-blocks': 'error',
      'no-multi-spaces': 'error',
      'no-return-await': 'error',
      'no-self-compare': 'error',
      'no-useless-call': 'error',
      'no-useless-concat': 'error',
      'no-useless-return': 'error',
      'no-void': 'error',
      radix: 'error',
      'wrap-iife': ['error', 'inside'],
      'no-label-var': 'error',
      'no-undef-init': 'error',
      'array-bracket-newline': ['error', 'consistent'],
      'array-bracket-spacing': ['error', 'never'],
      'array-element-newline': ['error', 'consistent'],
      'brace-style': ['error', '1tbs'],
      'comma-spacing': ['error', { before: false, after: true }],
      'comma-style': ['error', 'last'],
      'computed-property-spacing': ['error', 'never'],
      'consistent-this': ['error', 'self'],
      'eol-last': ['error', 'always'],
      'func-call-spacing': ['error', 'never'],
      'func-name-matching': 'error',
      'func-style': ['error', 'declaration', { allowArrowFunctions: true }],
      'function-call-argument-newline': ['error', 'never'],
      'function-paren-newline': ['error', 'multiline'],
      'implicit-arrow-linebreak': ['error', 'beside'],
      'jsx-quotes': ['error', 'prefer-double'],
      'key-spacing': ['error', { beforeColon: false, afterColon: true, mode: 'strict' }],
      'keyword-spacing': ['error', { before: true, after: true }],
      'multiline-comment-style': ['error', 'bare-block'],
      'multiline-ternary': ['error', 'never'],
      'new-parens': ['error', 'always'],
      'newline-per-chained-call': 'error',
      'no-array-constructor': 'error',
      'no-inline-comments': 0,
      'no-lonely-if': 'error',
      'no-mixed-operators': 'off',
      'no-multiple-empty-lines': ['error', { max: 2, maxEOF: 0, maxBOF: 0 }],
      'no-new-object': 'error',
      'no-tabs': 'error',
      'no-unneeded-ternary': 'error',
      'no-whitespace-before-property': 'error',
      'nonblock-statement-body-position': ['error', 'beside'],
      'object-curly-newline': ['error', { consistent: true }],
      'object-curly-spacing': ['error', 'always'],
      'object-property-newline': ['error', { allowMultiplePropertiesPerLine: true }],
      'one-var': ['error', 'never'],
      'one-var-declaration-per-line': ['error', 'initializations'],
      'operator-assignment': ['error', 'always'],
      'padded-blocks': ['error', 'never'],
      'quote-props': ['error', 'as-needed'],
      quotes: ['error', 'single'],
      semi: ['error', 'always'],
      'semi-spacing': ['error', { before: false, after: true }],
      'semi-style': ['error', 'last'],
      'space-before-blocks': 'error',
      'space-before-function-paren': [
        'error',
        { anonymous: 'never', named: 'never', asyncArrow: 'always' },
      ],
      'space-in-parens': ['error', 'never'],
      'space-unary-ops': 'error',
      'spaced-comment': ['error', 'always', { exceptions: ['-+'] }],
      'arrow-spacing': ['error', { before: true, after: true }],
      'generator-star-spacing': [
        'error',
        {
          before: false,
          after: true,
          anonymous: 'neither',
          method: { before: true, after: true },
        },
      ],
      'no-duplicate-imports': 'error',
      'no-useless-computed-key': 'error',
      'no-useless-constructor': 'error',
      'no-useless-rename': 'error',
      'no-var': 'error',
      'rest-spread-spacing': ['error', 'never'],
      'template-curly-spacing': ['error', 'never'],
      'vue/attribute-hyphenation': ['error', 'always', { ignore: ['viewBox'] }],
      'vue/custom-event-name-casing': 'off',
      'vue/html-closing-bracket-newline': 'error',
      'vue/html-self-closing': [
        'error',
        {
          html: { void: 'any', normal: 'any', component: 'any' },
          svg: 'always',
          math: 'always',
        },
      ],
      'vue/multiline-html-element-content-newline': [
        'error',
        { ignoreWhenEmpty: false, allowEmptyLines: true },
      ],
      'vue/name-property-casing': ['error', 'PascalCase'],
      'vue/singleline-html-element-content-newline': 'off',
      'vue/html-closing-bracket-spacing': 'off',
      'vue/no-reserved-keys': 'off',
      'import/order': 'error',
      'import/first': 'error',
      'import/no-mutable-exports': 'error',
      'import/no-unresolved': 'off',
      'arrow-parens': ['error', 'as-needed', { requireForBlockBody: true }],
      'prefer-const': ['error', { destructuring: 'any', ignoreReadBeforeAssign: false }],
      'dot-notation': ['error', { allowKeywords: true }],
      'object-shorthand': 'error',
    },
    settings: {
      'import/resolver': {
        node: { extensions: ['.js', '.mjs'] },
      },
    },
  }),

  // Доп. настройки парсинга для Vue SFC
  {
    files: ['**/*.vue'],
    languageOptions: {
      parser: vueParser,
      parserOptions: {
        parser: {
          js: '@babel/eslint-parser',
          ts: '@typescript-eslint/parser',
        },
        extraFileExtensions: ['.vue'],
        ecmaVersion: 'latest',
        requireConfigFile: false,
        sourceType: 'module',
      },
      globals: {
        ...globals.browser,
        ...globals.node,
      },
    },
  },

  // Prettier выключает конфликтующие правила форматирования
  eslintConfigPrettier,

  // Ваши требования к vue-template форматированию
  {
    files: ['**/*.vue'],
    rules: {
      // Если у тега >1 атрибута — каждый с новой строки (и первый тоже)
      'vue/max-attributes-per-line': ['error', { singleline: 1, multiline: 1 }],
      'vue/first-attribute-linebreak': ['error', { singleline: 'beside', multiline: 'below' }],
      'vue/html-closing-bracket-newline': ['error', { singleline: 'never', multiline: 'always' }],

      // Контент тега — всегда с новой строки
      'vue/singleline-html-element-content-newline': [
        'error',
        { ignoreWhenNoAttributes: false, ignoreWhenEmpty: true },
      ],
      'vue/multiline-html-element-content-newline': ['error', { allowEmptyLines: false }],
    },
  },
];
